version: '3'
services:
  build_service:
    build: .
    volumes:
      - java_project:/tmp/java_app/target/

  prod_service:
    image: tomcat
    depends_on:
      - build_service
    ports:
      - 8090:8080
    volumes:
      - java_project:/usr/local/tomcat/webapps/

volumes:
  java_project:
